apiVersion: serving.knative.dev/v1
kind: Service
metadata:
 name: APP_NAME
spec:
  template:
    spec:
      containers:
        - image: CONTAINER_IMAGE
          imagePullPolicy: IfNotPresent
          name: APP_NAME
          ports:
            - containerPort: 8080
              name: http1
              protocol: TCP
